#!/bin/sh -eu

tmpdir="`mktemp -d`"
target="`readlink -f initial-$1.tar.gz`"

echo Device name: "$1"
echo IP address: "$2"
echo Initial password: "$3"
echo Writing to: "$target"

pass_sha256="`echo -n "$3" | openssl dgst -sha256 | sed 's/^.* //'`"
pass_shadow="`echo -n "$3" | openssl passwd -1 -stdin`"

rsync -a "`dirname $0`/template/" "$tmpdir/"

cd "$tmpdir"

sed -i "s|password '.*'|password '$pass_sha256'|" etc/config/glconfig
sed -i "s|root:[^:]*|root:$pass_shadow|" etc/shadow
ssh-keygen -t ed25519 -f root/.ssh/id_ed25519 -C "$1" -N '' -q
sed -i "s|option hostname '.*'|option hostname '$1'|" etc/config/system
sed -i "s|option hostname '.*'|option hostname '$1'|" etc/config/network
sed -i "s|10\.101\.0\.50|$2|" etc/config/dhcp
sed -i "s|10\.101\.0\.50|$2|" etc/config/network

echo -n 'Public key: '
cat root/.ssh/id_ed25519.pub

tar --owner root --group root -czf "$target" *
