#!/bin/sh -eu

while true; do
    ssh -T jkl.hacklab.fi -o BatchMode=yes -o ServerAliveInterval=15 -o "Tunnel=ethernet" -w 0 -o "PermitLocalCommand=true" -o "LocalCommand=ip link set tap0 up && brctl addif br0 tap0" || true
    sleep 15
done
